version: "3"
services:
  db:
    image: mysql
    container_name: db
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=zaq12wsx
    ports:
      - 3306:3306
  pma:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8085:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=zaq12wsx
    depends_on:
      - db
  php:
    image: egzamin:1.0
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - 8086:80
    depends_on:
      - db

volumes:
  db:
